import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { resolve } from "path";

export default defineConfig({
  root: "./",
  plugins: [react()],
  resolve: {
    dedupe: ["three"],
  },
  build: {
    outDir: "dist",
    emptyOutDir: true,
    rollupOptions: {
      input: {
        main: resolve(__dirname, "index.html"),
        day01: resolve(__dirname, "day-01-rotating-cube/index.html"),
        day01Project: resolve(__dirname, "day01-project/index.html"),
        day02: resolve(__dirname, "day-02-orbitctrl-datgui/index.html"),
        day03: resolve(__dirname, "day-03-lighting-materials/index.html"),
        day04: resolve(__dirname, "day-04-gltf-hdr/index.html"),
        day05: resolve(__dirname, "day-05-modern-api/index.html"),
        day06: resolve(__dirname, 'day-06-glsl-fundamentals/index.html'),
        day06a: resolve(__dirname, "day-06-glsl-fundamentals/06a-shapes.html"),
        day06b: resolve(__dirname, "day-06-glsl-fundamentals/06b-patterns.html"),
        day06c: resolve(__dirname, "day-06-glsl-fundamentals/06c-radar.html"),
        day06d: resolve(__dirname, "day-06-glsl-fundamentals/06d-animated.html"),
        day06e: resolve(__dirname, "day-06-glsl-fundamentals/06e-song.html"),
        day06f: resolve(__dirname, "day-06-glsl-fundamentals/06f-diamond.html"),
        day06g: resolve(__dirname, "day-06-glsl-fundamentals/06g-gradient-warp.html"),
        day07: resolve(__dirname, "day-07/index.html"),
        day07a: resolve(__dirname, "day-07/07a-shear-only.html"),
        day08: resolve(__dirname, "day-08-shader-material/index.html"),
        day09: resolve(__dirname, "day-09-throttle-bar/index.html"),
        day09a: resolve(__dirname, "day-09a-rpm-arc/index.html"),
        day09b: resolve(__dirname, "day-09b-gear-indicator/index.html"),
        day09c: resolve(__dirname, "day-09c-sector-times/index.html"),
        day10: resolve(__dirname, "day-10-hud-assembly/index.html"),
        day11: resolve(__dirname, "day-11-camera-curves/index.html"),
        day12: resolve(__dirname, "day-12-particles/index.html"),
        day13: resolve(__dirname, "day-13-instanced/index.html"),
        day14: resolve(__dirname, "day-14-post-processing/index.html"),
        day15: resolve(__dirname, "day-15-transitions/index.html"),
        day16: resolve(__dirname, "day-16-pixelation/index.html"),
        day16Reference: resolve(__dirname, "day-16-reference/index.html"),
        day16a: resolve(__dirname, "day-16a-domain-warp-pixelated/index.html"),
        day16b: resolve(__dirname, "day-16b-feedback-ink/index.html"),
        day16c: resolve(__dirname, "day-16c-bake-to-texture/index.html"),
        day16d: resolve(__dirname, "day-16d-dither-appear/index.html"),
        day16e: resolve(__dirname, "day-16e-capstone/index.html"),
        day17: resolve(__dirname, "day-17/index.html"),
        day18: resolve(__dirname, "day-18/index.html"),
        day19: resolve(__dirname, "day-19/index.html"),
        day19a: resolve(__dirname, "day-19a/index.html"),
        day20: resolve(__dirname, "day-20/index.html"),
        day21: resolve(__dirname, "day-21/index.html"),
        day22: resolve(__dirname, "day-22-baked-background/index.html"),
        day22a: resolve(__dirname, "day-22a/index.html"),
        day22b: resolve(__dirname, "day-22b/index.html"),
        day22c: resolve(__dirname, "day-22c/index.html"),
        day23: resolve(__dirname, "day-23/index.html"),
      },
    },
  },
});
